### ISSUE TITLE
File "preprocess.py", line 255     c_row = [*c_head, *n_tail]

### ISSUE THREAD

**Issue by hhassanien** [TrackLiao/TexyGen-Noise#1]
while running the "python preprocess.py" the following error shows.. please assist

/TexyGen-Noise/data/noise$ python preprocess.py
  File "preprocess.py", line 255
    c_row = [*c_head, *n_tail]
             ^
SyntaxError: invalid syntax

**Comment by ChakyuLiao** [comment]
Try "python3 preprocess.py", does the error still pop out?

**Comment by hhassanien** [comment]
I think it has worked well.. Thank you very much. One more thing, I do know this work is based on the Texygen platform. 

I have been trying to generate text from Texygen but had failed to obtain the text out of it. Would be very thankful if you'd get the chance to help out with that as well PLEEEEEASE. 
In addition to the error mentioned in the below link; I can't find which output file is the generated text out of the platform
https://github.com/geek-ai/Texygen/issues/35

**Comment by hhassanien** [comment]
python3 preprocess.py WORKS .. Thank you very much ..

I have now tried :~/TexyGen-Noise$ bash run.sh real --  and the outcome is as follows: 

---------------------------------------------------------------------------
testing with real word
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from models.rankgan.Rankgan import Rankgan
  File "/home/hossam_hassanien/TexyGen-Noise/models/rankgan/Rankgan.py", line 5, in <module>
    from models.rankgan.RankganDiscriminator import Discriminator
  File "/home/hossam_hassanien/TexyGen-Noise/models/rankgan/RankganDiscriminator.py", line 191
    self.scores = tf.reshape(self.feature @ tf.transpose(self.reference, perm=[1, 0]), [-1])
                                          ^
SyntaxError: invalid syntax
---------------------------------------------------------------------------

On the other hand, I do know that this work is based on Texygen. I have been trying to generate text from Texygen but did not succeed. I dont know where the output text gets produced plus I am facing the following error (please see link below). Would HIGHLY appreciate it if you would be able to assist with that as well PLEEEEASE ..

https://github.com/geek-ai/Texygen/issues/35

THANK you very much in advance.

**Comment by ChakyuLiao** [comment]
For the `run.sh`, you can simply modified `run.sh` and change all line with "python" into "python3" (my default python is python3 so...), you can also change your default python into python3, so the quote you requested on `geek-ai/Texygen#35` will be solved. 
After training your data, the generated file will be in `./save/test_file.txt`
For more details, I suggest you to read the code of TexyGen and understand how their codes works :)
